addressLocApp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('addressLocator.urls', namespace="addressLocator")),
]

addressLocator/urls.py
from django.urls import path

from . import views

app_name = "addressLocator"

urlpatterns = [
    path('', views.index, name='index'),
]

addressLocator/models.py
from django.db import models

# Create your models here.

addressLocator/views.py
# Create your views here.
import os
from django.shortcuts import render, HttpResponse
import openpyxl
from pygeocoder import Geocoder
import pandas as pd
import numpy as np

from geopy.geocoders import Nominatim


def index(request):
    if "GET" == request.method:
        return render(request, 'addressLocator/index.html', {})
    else:
        nom = Nominatim(user_agent="addressLocator")
        
        excel_file = request.FILES["excel_file"]
        
        df = pd.read_excel(excel_file)
        
        df['Address'] = df['Address1']+", "+df['Address2']+", "+df['Address3']+", "+df['Address4']
        
        #df.head()
        df["Coordinates"] = df["Address"].apply(nom.geocode)
        
        df["Latitude"] = df["Coordinates"].apply(lambda x : x.latitude if x != None else None)      
        df["Longitude"] = df["Coordinates"].apply(lambda x : x.longitude if x != None else None)
     
        df.to_excel('updated_addresses.xls', sheet_name='Sheet1', index=False, engine='xlsxwriter')          
    
    return HttpResponse("Your File has been saved, do check inside your project folder!")

addressLocator/templates/addressLocator/index.html
<html>
    <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <title>
            Excel file upload and processing
        </title>
    </head>
    <body style="margin-top: 30px;margin-center: 30px;">
    <div class="container">
        <form action="{% url "addressLocator:index" %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file"
                   title="Upload excel file"
                   name="excel_file"
                   style="border: 1px solid black; padding: 5px;"
                   required="required">
            <p>
            <input type="submit"
                   value="Upload"
                   style="border: 1px solid green; padding:5px; border-radius: 2px; cursor: pointer;">
        </form>

        <p></p>
        <hr>

        {% for row in excel_data %}
            {% for cell in row %}
                {{ cell }}&nbsp;&nbsp;
            {% endfor %}
            <br>
        {% endfor %}
        </div>
    </body>
</html>